## Site info test 1 ##
######################

baseurl = "https://nutspubcrawl.com/"

#Testing baseurl
#baseurl = "http://localhost.nutspubcrawl.com/"
canonifyURLs = true  # Transform all URLs to absolute using baseURL
theme = "nutspubcrawl"
MetaDataFormat = "yaml"
enableRobotsTXT = true


[author]
    name = "Jeremie Leroy"

[Taxonomies]
    tag = "tags"
    topic = "topics"
    categories = "categories"


[params]
# 1000 free emails per month
# with formspree.io
email = "info@nutspubcrawl.com"
twitter = "https://twitter.com/NutsPubCrawl"
handle = "@NutsPubCrawl"
address = """118 King's Cross Rd.
<br>London WC1X 9DS
<br>United Kingdom</p>"""

custom_css = ["css/assets/bootstrap-material-design-font/css/material.min.css",
"css/assets/web/assets/mobirise-icons/mobirise-icons.min.css",
"css/assets/et-line-font-plugin/style.min.css",
"css/assets/tether/tether.min.css",
"css/assets/bootstrap/css/bootstrap.min.css",
"css/assets/dropdown/css/style.min.css",
"css/assets/animate.css/animate.min.css",
"css/assets/socicon/css/styles.min.css",
"css/assets/theme/css/style.min.css",
"css/assets/mobirise/css/mbr-additional.min.css",
]

[params.widgets]
    categories = "true"

## Multilingual settings ##
###########################

defaultContentLanguage = "en"

## Per lang settings ##
#######################

[Languages]
[Languages.en]
title = "Nuts Pub Crawls London"
weight = 1
defaultKeywords = ["Pub crawls London", "pub crawl London", "pub crawl","crawl london"]
defaultDescription = "Pub Crawls in London, it is probably the best way to party and discover the clubs and pubs of London with Nuts Pub Crawl, all our tours aim to provide a great night out."
disqusShortname = "nutspubcrawl"

[Languages.fr]
title = "Londres Pub Crawls Nuts"
weight = 2
defaultKeywords = ["Pub Crawl a londres", "pub crawl londres", "barathon","crawl londres"]
defaultDescription = "Faire la tournée des clubs du centre de Londres avec Nuts Pub Crawl, c'est l'idée de faire un barathon mais avec des club"
disqusShortname = "nutspubcrawlfr"


[Languages.es]
title = "Nuts Pub Crawls Londres"
weight = 3
defaultKeywords = ["Pub crawls Londres", "pub crawl Londres", "pub crawl","crawl londres"]
defaultDescription = "Pub Crawls en Londres, es la mejor forma para salir de fiesta en Londres y descubrir las discotecas y bares más populares con Nuts Pub Crawl, todos nuestros tours son garantía de una gran noche."
disqusShortname = "nutspubcrawles"
